services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: cc_user
      POSTGRES_PASSWORD: cc_password
      POSTGRES_DB: coder_chat
    volumes:
      - pg_data:/var/lib/postgresql/
    ports:
      - "25432:5432"

volumes:
  pg_data: